### ISSUE TITLE
Default value of parameter

### ISSUE THREAD

**Issue by liyichao108** [mihaidusmanu/pycolmap#14]
Hi @mihaidusmanu , thanks for the Excellent tool. 
I find that the default value of  parameter "max_error_px" in function "absolute_pose_estimation" is 12.0, however it is 4.0 in function "essential_matrix_estimation" and "fundamental_matrix_estimation". 
`// Absolute pose.
    m.def("absolute_pose_estimation", &absolute_pose_estimation,
          py::arg("points2D"), py::arg("points3D"),
          py::arg("camera_dict"),
          py::arg("max_error_px") = 12.0,
          "Absolute pose estimation with non-linear refinement.");

    // Essential matrix.
    m.def("essential_matrix_estimation", &essential_matrix_estimation,
          py::arg("points2D1"), py::arg("points2D2"),
          py::arg("camera_dict1"), py::arg("camera_dict2"),
          py::arg("max_error_px") = 4.0,
          "LORANSAC + 5-point algorithm.");

    // Fundamental matrix.
    m.def("fundamental_matrix_estimation", &fundamental_matrix_estimation,
          py::arg("points2D1"), py::arg("points2D2"),
          py::arg("max_error_px") = 4.0,
          "LORANSAC + 7-point algorithm.");`

I would like to know why the default value of "max_error_px" is so big in function "absolute_pose_estimation".
Hope to hear from you soon. Thank you so much!

**Comment by mihaidusmanu** [comment]
Here, we are simply using the default values used in COLMAP two-view geometry / pose estimation - these values were tuned for internet images with SIFT feature extraction.

It is recommended to tune these values for your specific application / features / resolution. For instance, if image are very high res so you need to downsample them before feature extraction, then a higher threshold would be needed.
