### ISSUE TITLE
Dense Reconstruction?

### ISSUE THREAD

**Issue by mattbev** [mihaidusmanu/pycolmap#18]
Very useful repo! Wondering if there is any intention to include dense reconstruction in this binding? As far as I can tell several of the functions necessary for it are not yet included (sift keypoint matching, etc), but perhaps I've just missed them. 

Thanks!

**Comment by mattbev** [comment]
(may be a repeat of #17)

**Comment by Skydes** [comment]
Hi! Sorry for the late reply. Currently we only bind a limited set of functions. For dense reconstruction you will need to call the COLMAP binaries from the command line. We are slowly binding more functions, such as the main SfM objects in https://github.com/mihaidusmanu/pycolmap/pull/20. It should be fairly straightforward to add other steps of the pipeline and any contribution is welcome!

**Comment by Skydes** [comment]
@Phil26AT has added support for MVS in the `cuda-bindings` branch. This requires COLMAP to be built with CUDA support:
https://github.com/colmap/pycolmap/blob/b30a4501b71364aa19adc990a401177c39a5ae62/pipeline/mvs.cc#L230-L247
Please let us know if you try it out!
