### ISSUE TITLE
Question regarding input of Pose Refinement?

### ISSUE THREAD

**Issue by vahidEttehadi** [mihaidusmanu/pycolmap#23]
Hi, I am trying to use colmap for pose correction and I end up here. I was wondering what's the length of tvec and qvec in the input? Should it be the same as the length of 2D-3D points (N)? Also, I have different intrinsics for each view. How I should feed it to pose refinement? it looks it only accept the same intrinsics for all views. Also, I don't understand exactly what's inlier_mask?

Please let me know if there is documentation for pose refinement. Thanks!

**Comment by mihaidusmanu** [comment]
The pose refinement only refines one pose / camera at a time. If you have multiple cameras you will need to call the function multiple times, once for each set of 2D-3D matches, initial pose, and intrinsics.

The qvec is a 4-dimensional vector and tvec is a 3-dimensional one representing the initial pose in COLMAP convention (https://colmap.github.io/format.html). Inlier mask is a boolean vector which marks as True the 2D-3D matches which are inliers (i.e., the ones to be considering during optimization). If all your matches are to be considered, you can pass a vector full of True with the size N.

**Comment by vahidEttehadi** [comment]
Ok. Great. Thanks @mihaidusmanu.
