### ISSUE TITLE
Add bindings for homography fitting

### ISSUE THREAD

**Issue by mihaidusmanu** [mihaidusmanu/pycolmap#29]
Since #24 added homography decomposition, it would be good to also expose homography estimation using LO-RANSAC based on https://github.com/colmap/colmap/blob/9f3a75ae9c72188244f2403eb085e51ecf4397a8/src/estimators/two_view_geometry.cc#L277.

**Comment by Skydes** [comment]
Added in https://github.com/mihaidusmanu/pycolmap/pull/31
