### ISSUE TITLE
Difference between SimplePinhole and Pinhole

### ISSUE THREAD

**Issue by Zumbalamambo** [mihaidusmanu/pycolmap#3]
I see that there are two types of pinhole camera models. what is the difference between the "SimplePinhole" and "Pinhole"? In case if I would like to include both `fx` as well as `fy`, should I include it in params as `[fx,fy,cx,cy]` or `[fx,cx,fy,cy]`? I would like to know its order.

**Comment by mihaidusmanu** [comment]
The ordering is the same as in COLMAP, i.e., [fx, fy, cx, cy]. Please refer to the following file for more details regarding camera models https://github.com/colmap/colmap/blob/dev/src/base/camera_models.h#L198.

**Comment by Zumbalamambo** [comment]
Thank you for the great library. Looking forward to seeing more functions :)
