### ISSUE TITLE
Installation error: Could not find a package configuration file provided by "Qt5" with any of the following names:

### ISSUE THREAD

**Issue by yopi1838** [mihaidusmanu/pycolmap#7]
Hi. Thank you for the great work!

I have found this error when installing pycolmap. I have confirmed that COLMAP is installed. I have tried everything mentioned in StackOverflow to no avail. 

I am using M1 MacBook Pro.

Here are the error from Terminal:

Processing /Users/yopiprabowooktiovan/Desktop/Projects/pycolmap
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py'"'"'; __file__='"'"'/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-wheel-vwndny11
       cwd: /private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/
  Complete output (100 lines):
  running bdist_wheel
  running build
  running build_ext
  ['cmake', '/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/build/lib.macosx-10.9-x86_64-3.8', '-DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8', '-DCMAKE_BUILD_TYPE=Release']
  -- The C compiler identification is AppleClang 12.0.0.12000032
  -- The CXX compiler identification is AppleClang 12.0.0.12000032
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Found required Ceres dependency: Eigen version 3.3.9 in /usr/local/include/eigen3
  -- Found required Ceres dependency: glog
  -- Found required Ceres dependency: gflags
  -- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, AccelerateSparse, SchurSpecializations, Multithreading]
  -- Found Boost: /usr/local/lib/cmake/Boost-1.75.0/BoostConfig.cmake (found version "1.75.0") found components: program_options filesystem system unit_test_framework
  -- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0")
  -- Found Eigen
  --   Includes : /usr/local/include/eigen3
  -- Found FreeImage
  --   Includes : /usr/local/include
  --   Libraries : /usr/local/lib/libfreeimage.dylib
  -- Found Glog
  --   Includes : /usr/local/include
  --   Libraries : /usr/local/lib/libglog.dylib
  -- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/OpenGL.framework
  -- Found Glew
  --   Includes : /usr/local/include
  --   Libraries : /usr/local/lib/libGLEW.dylib
  CMake Error at /usr/local/share/colmap/COLMAPConfig.cmake:106 (find_package):
    By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "Qt5", but
    CMake did not find one.
  
    Could not find a package configuration file provided by "Qt5" (requested
    version 5.4) with any of the following names:
  
      Qt5Config.cmake
      qt5-config.cmake
  
    Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
    to a directory containing one of the above files.  If "Qt5" provides a
    separate development package or SDK, be sure it has been installed.
  Call Stack (most recent call first):
    CMakeLists.txt:7 (find_package)
  
  
  CMake Error at CMakeLists.txt:7 (find_package):
    Found package configuration file:
  
      /usr/local/share/colmap/COLMAPConfig.cmake
  
    but it set COLMAP_FOUND to FALSE so package "COLMAP" is considered to be
    NOT FOUND.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/build/temp.macosx-10.9-x86_64-3.8/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/build/temp.macosx-10.9-x86_64-3.8/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py", line 62, in <module>
      setup(
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py", line 32, in run
      self.build_extension(ext)
    File "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py", line 59, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/build/lib.macosx-10.9-x86_64-3.8', '-DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pycolmap
  Running setup.py clean for pycolmap
Failed to build pycolmap
Installing collected packages: pycolmap
    Running setup.py install for pycolmap ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py'"'"'; __file__='"'"'/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-record-eifp479z/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/pycolmap
         cwd: /private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/
    Complete output (102 lines):
    running install
    running build
    running build_ext
    ['cmake', '/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/build/lib.macosx-10.9-x86_64-3.8', '-DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8', '-DCMAKE_BUILD_TYPE=Release']
    -- The C compiler identification is AppleClang 12.0.0.12000032
    -- The CXX compiler identification is AppleClang 12.0.0.12000032
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE
    -- Found required Ceres dependency: Eigen version 3.3.9 in /usr/local/include/eigen3
    -- Found required Ceres dependency: glog
    -- Found required Ceres dependency: gflags
    -- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, AccelerateSparse, SchurSpecializations, Multithreading]
    -- Found Boost: /usr/local/lib/cmake/Boost-1.75.0/BoostConfig.cmake (found version "1.75.0") found components: program_options filesystem system unit_test_framework
    -- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0")
    -- Found Eigen
    --   Includes : /usr/local/include/eigen3
    -- Found FreeImage
    --   Includes : /usr/local/include
    --   Libraries : /usr/local/lib/libfreeimage.dylib
    -- Found Glog
    --   Includes : /usr/local/include
    --   Libraries : /usr/local/lib/libglog.dylib
    -- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/OpenGL.framework
    -- Found Glew
    --   Includes : /usr/local/include
    --   Libraries : /usr/local/lib/libGLEW.dylib
    CMake Error at /usr/local/share/colmap/COLMAPConfig.cmake:106 (find_package):
      By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "Qt5", but
      CMake did not find one.
    
      Could not find a package configuration file provided by "Qt5" (requested
      version 5.4) with any of the following names:
    
        Qt5Config.cmake
        qt5-config.cmake
    
      Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
      to a directory containing one of the above files.  If "Qt5" provides a
      separate development package or SDK, be sure it has been installed.
    Call Stack (most recent call first):
      CMakeLists.txt:7 (find_package)
    
    
    CMake Error at CMakeLists.txt:7 (find_package):
      Found package configuration file:
    
        /usr/local/share/colmap/COLMAPConfig.cmake
    
      but it set COLMAP_FOUND to FALSE so package "COLMAP" is considered to be
      NOT FOUND.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/build/temp.macosx-10.9-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    See also "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/build/temp.macosx-10.9-x86_64-3.8/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py", line 62, in <module>
        setup(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py", line 32, in run
        self.build_extension(ext)
      File "/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py", line 59, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/build/lib.macosx-10.9-x86_64-3.8', '-DPYTHON_EXECUTABLE=/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py'"'"'; __file__='"'"'/private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-req-build-qx4m3ciu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/79/z2wsfkyj2vs8hp7nb62rv9vm0000gn/T/pip-record-eifp479z/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/pycolmap Check the logs for full command output.

**Comment by mihaidusmanu** [comment]
I have only tested the install on Linux so I sadly cannot help - will leave the issue open maybe someone else can.

Judging by the error message, it seems like Qt5 is not installed / detected. Did you compile COLMAP from sources or simply download the pre-built binaries?

**Comment by tsattler** [comment]
When building Colmap on Mac, you need the `-DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5` flag for cmake. See https://colmap.github.io/install.html#id2 .

**Comment by womackj1** [comment]
@tsattler  I included the Qt5 flag and followed the Mac build from source instructions and ran into the same issue.

**Comment by ZZWang21** [comment]
Excuse me, @tsattler I tried this on Windows, but it still does not work.

**Comment by tsattler** [comment]
I never tried building Colmap on Windows.

**Comment by gcostello65** [comment]
Wanted to add that in the colmap installation documentation, the path to qt5 is /usr/local/... but with apple silicon, homebrew installs to /opt/homebrew... so I had to update the commands to reflect the binary locations.
