### ISSUE TITLE
What's the definition of absolute pose

### ISSUE THREAD

**Issue by Grem-Lin** [mihaidusmanu/pycolmap#9]
Suppose the output of absolute_pose_estimation has the output as follows:
ret['qvec'], ret['tvec'].
May I ask what's the definition of qvec and tvec? I hope to have the answer like for example, qvec represents rotation from camera frame to object frame, in unit quaternion form. tvec represent translation from camera frame to object frame, expressed in camera frame.

Thanks!

**Comment by mihaidusmanu** [comment]
Hello. We are using the colmap pose convention - i.e., world-to-camera with qvec in format w, x, y, z and tvec in format x, y, z (see https://colmap.github.io/format.html#images-txt). Thus, given a 3D point P, to obtain the coordinates in camera frame, you have to do something along the lines:
```
def mat_from_quat(quat):
    # quat is [w, x, y, z]
    from scipy.spatial.transform import Rotation as R
    rot = R.from_quat([quat[1], quat[2], quat[3], quat[0]]) # expects [x, y, z, w]
    mat = rot.as_matrix()
    return mat

R = mat_from_quat(qvec)
P_camera = R @ P + tvec
```

**Comment by alexs7** [comment]
@mihaidusmanu This should work also when the points are in camera coordinates ? 
At the end of the end they are just 3D points (does it matter if they are in camera space or world ) ?
